FROM node:10

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000

CMD ["npm", "start"]





#FROM alpine
#RUN apk update && apk upgrade
#RUN apk add nodejs

#WORKDIR /app
#ADD . /app
#ENTRYPOINT [ "node", "server.js" ]